### PR TITLE
Spec and config cleanup

### PR DESCRIPTION
**Pull request by yurrriq**
The `project_plugins` change comes after a chat with Tristan. The rest is pretty straightforward.

### CODE REVIEW

**Comment by yurrriq** [comment]
Please excuse the noise.. I've adopted `git-flow` on this repo now.

**Comment by yurrriq** [comment]
I need to rebase this.

**Comment by oubiwann** [comment]
Thanks!

**Comment by oubiwann** [comment]
Hrm, so I merged this, ran the lodox command, and lodox now seems to download all the repos that are in `project_plugins` ...

I think I liked the profile approach better. But I'll wait to see if this is really what's happening (I didn't dig too deeply).

**Comment by oubiwann** [comment]
Yeah, I just confirmed ... deleted all of `_build` and ran `make check` and everything was downloaded and installed, not just ltest and its deps, but lodox and all of its deps too.

I'm going to revert the changes to `rebar.config` and put the test and other profiles back in ...

**Comment by yurrriq** [comment]
That's because you're in the project. When you build lmug as a dep it won't.

**Comment by yurrriq** [comment]
If you want to delay downloading Lodox as long as possible, you can put it in the `docs` profile, but recent versions run in that namespace automatically so there's no need to `as docs`.

**Comment by yurrriq** [comment]
See also quasiquoting/lodox#60

**Pull request merged**
