### PR TITLE
Fix the tests!

### LINKED ISSUE #25: Use binaries instead of strings
Related: #22, #15

### PR DESCRIPTION
**Pull request by yurrriq**
Use binaries and spec-matching defaults. :tada:

Fixes #25, I think.

### CODE REVIEW

**Comment by yurrriq** [comment]
Needs to be rebased.

**Comment by oubiwann** [comment]
I've rebased and resolved conflicts.

**Comment by yurrriq** [comment]
Sweet, thanks!

**Comment by yurrriq** [comment]
Ok something went weirdly wrong..

**Pull request merged**
